c = open('app.py', 'rb').read().decode('utf-8')

old = (
    '    if not is_supabase_enabled() or not supabase:\n'
    '        return jsonify({"ok": False, "error": "Password reset is unavailable right now."}), 503\n'
    '\n'
    '    payload = request.get_json(silent=True) or {}\n'
    '    if not payload and request.form:\n'
    '        payload = request.form.to_dict() or {}\n'
    '    email = normalize_email(payload.get("email", ""))\n'
    '    if not email:\n'
    '        return jsonify({"ok": False, "error": "Email is required."}), 400\n'
    '    if not is_valid_email(email):\n'
    '        return jsonify({"ok": False, "error": "Please enter a valid email address."}), 400\n'
    '\n'
    '    # Surface not-found explicitly when service-role access is available.\n'
    '    if is_supabase_service_role_enabled():\n'
    '        try:\n'
    '            existing_auth_user = find_supabase_auth_user_by_email(email)\n'
    '            if not existing_auth_user:\n'
    '                print(f"FORGOT_PASSWORD: auth user not found for {safe_email_for_log(email)}")\n'
    '                return jsonify({"ok": False, "error": "No account found for this email address."}), 404\n'
    '        except Exception as lookup_exc:\n'
    '            log_exception("forgot password lookup failed", lookup_exc, email=safe_email_for_log(email))\n'
    '\n'
    '    try:\n'
    '        reset_redirect = (\n'
    '            (os.environ.get("FRESHWASH_PASSWORD_RESET_REDIRECT_TO") or "").strip()\n'
    '            or "http://localhost:5000/reset-password"\n'
    '        )\n'
    '        print(\n'
    '            "FORGOT_PASSWORD: sending reset",\n'
    '            f"email={safe_email_for_log(email)}",\n'
    '            f"redirect_to={reset_redirect}",\n'
    '        )\n'
    '        response = supabase.auth.reset_password_for_email(\n'
    '            email,\n'
    '            {"redirect_to": reset_redirect},\n'
    '        )\n'
    '        print(f"FORGOT_PASSWORD: supabase response={response!r}")\n'
    '        return jsonify({"ok": True, "message": "Check your email"})\n'
    '    except Exception as exc:\n'
    '        log_exception("forgot password send failed", exc, email=safe_email_for_log(email))\n'
    '        message = extract_supabase_error_message(exc)\n'
    '        print(\n'
    '            "FORGOT_PASSWORD: send failed",\n'
    '            f"email={safe_email_for_log(email)}",\n'
    '            f"error={message}",\n'
    '        )\n'
    '        lowered = message.lower()\n'
    '        if "user not found" in lowered:\n'
    '            return jsonify({"ok": False, "error": "No account found for this email address."}), 404\n'
    '        if "invalid email" in lowered:\n'
    '            return jsonify({"ok": False, "error": "Please enter a valid email address."}), 400\n'
    '        return jsonify({"ok": False, "error": "Unable to send reset link right now. Please try again."}), 500\n'
)

new = (
    '    payload = request.get_json(silent=True) or {}\n'
    '    if not payload and request.form:\n'
    '        payload = request.form.to_dict() or {}\n'
    '    email = normalize_email(payload.get("email", ""))\n'
    '    if not email:\n'
    '        return jsonify({"ok": False, "error": "Email is required."}), 400\n'
    '    if not is_valid_email(email):\n'
    '        return jsonify({"ok": False, "error": "Please enter a valid email address."}), 400\n'
    '\n'
    '    if not is_supabase_enabled() or not supabase:\n'
    '        return jsonify({"ok": False, "error": "Password reset is unavailable right now."}), 503\n'
    '\n'
    '    try:\n'
    '        reset_redirect = (\n'
    '            (os.environ.get("FRESHWASH_PASSWORD_RESET_REDIRECT_TO") or "").strip()\n'
    '            or "http://localhost:5000/reset-password"\n'
    '        )\n'
    '        supabase.auth.reset_password_for_email(email, {"redirect_to": reset_redirect})\n'
    '    except Exception as exc:\n'
    '        log_exception("forgot password send failed", exc, email=safe_email_for_log(email))\n'
    '    return jsonify({"ok": True, "message": "If the email exists, a reset link has been sent."})\n'
)

assert old in c, "Target not found in app.py!"
c = c.replace(old, new, 1)
open('app.py', 'wb').write(c.encode('utf-8'))
print("Done.")
