create extension if not exists pgcrypto;

-- ============================================================
-- FreshWash — Full Schema (bookings + profiles)
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- ── Profiles table ──────────────────────────────────────────
create table if not exists public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text unique not null,
  full_name  text not null,
  phone      text,
  address    text,
  role       text not null default 'customer',
  created_at timestamptz default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists avatar text;
alter table public.profiles add column if not exists role text not null default 'customer';
alter table public.profiles add column if not exists otp_code text;
alter table public.profiles add column if not exists otp_expiry timestamptz;
alter table public.profiles add column if not exists is_verified boolean not null default false;
alter table public.profiles add column if not exists created_at timestamptz default now();
alter table public.profiles alter column email set not null;
alter table public.profiles alter column role set default 'customer';
update public.profiles set role = 'customer' where role is null or role = '' or role = 'user';
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles
  add constraint profiles_role_check
  check (role in ('admin', 'customer'));

-- Repair incorrect legacy FK where profiles.id points to public.users instead of auth.users.
-- This is idempotent and safe to run multiple times.
alter table public.profiles drop constraint if exists profiles_id_fkey;

do $$
begin
  if not exists (
    select 1
    from pg_constraint c
    join pg_class t on c.conrelid = t.oid
    join pg_namespace n on t.relnamespace = n.oid
    where n.nspname = 'public'
      and t.relname = 'profiles'
      and c.contype = 'f'
      and c.conname = 'profiles_id_fkey'
  ) then
    alter table public.profiles
      add constraint profiles_id_fkey
      foreign key (id)
      references auth.users(id)
      on delete cascade
      not valid;
  end if;
end $$;

-- Validate once data is aligned. If legacy rows do not map to auth.users yet,
-- this statement can fail; keep the FK as NOT VALID and fix rows by email first.
alter table public.profiles validate constraint profiles_id_fkey;

alter table public.profiles enable row level security;

drop policy if exists "Users can view own profile"   on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);


-- Machines table
create table if not exists public.machines (
  id             integer generated by default as identity unique,
  machine_number integer primary key,
  name          text not null,
  status        text not null default 'Available',
  load_type     text not null default 'Medium',
  enabled       boolean not null default true,
  updated_at    timestamptz default now()
);

alter table public.machines add column if not exists id integer;
alter table public.machines add column if not exists name text;
alter table public.machines add column if not exists status text not null default 'Available';
alter table public.machines add column if not exists load_type text not null default 'Medium';
alter table public.machines add column if not exists enabled boolean not null default true;
alter table public.machines add column if not exists updated_at timestamptz default now();
update public.machines
set status = 'Available'
where status not in ('Available', 'In Use', 'Maintenance', 'Disabled', 'Unavailable');
alter table public.machines drop constraint if exists machines_status_check;
alter table public.machines
  add constraint machines_status_check
  check (status in ('Available', 'In Use', 'Maintenance', 'Disabled', 'Unavailable'));
update public.machines
set id = machine_number
where id is null and machine_number is not null;
update public.machines
set name = coalesce(name, 'Machine ' || machine_number::text)
where name is null;
update public.machines
set enabled = false
where status in ('Maintenance', 'Disabled', 'Unavailable');
create unique index if not exists machines_id_unique on public.machines(id);


-- ── Bookings table ──────────────────────────────────────────
create table if not exists public.bookings (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid references auth.users(id) on delete cascade not null,
  full_name    text not null,
  phone        text not null,
  address      text not null,
  pickup_address text,
  service_type text not null,
  machine      text,
  load_type    text,
  pickup_date  date not null,
  pickup_time  time not null,
  weight       numeric(6,2) not null,
  total_price  numeric(10,2),
  delivery_option text default 'Pickup',
  payment_method text,
  reference_number text,
  payment_reference text,
  payment_proof text,
  proof_image text,
  payment_status text default 'Pending',
  notes        text,
  status       text not null default 'Pending',
  created_at   timestamptz default now()
);

alter table public.bookings add column if not exists full_name text;
alter table public.bookings add column if not exists phone text;
alter table public.bookings add column if not exists address text;
alter table public.bookings add column if not exists service_type text;
alter table public.bookings add column if not exists machine text;
alter table public.bookings add column if not exists load_type text;
alter table public.bookings add column if not exists weight numeric(6,2);
alter table public.bookings add column if not exists total_price numeric(10,2);
alter table public.bookings add column if not exists delivery_option text default 'Pickup';
alter table public.bookings add column if not exists pickup_date date;
alter table public.bookings add column if not exists pickup_time time;
alter table public.bookings add column if not exists notes text;
alter table public.bookings add column if not exists status text not null default 'Pending';
alter table public.bookings add column if not exists created_at timestamptz default now();
alter table public.bookings add column if not exists pickup_address text;
alter table public.bookings add column if not exists payment_method text;
alter table public.bookings add column if not exists reference_number text;
alter table public.bookings add column if not exists payment_reference text;
alter table public.bookings add column if not exists payment_proof text;
alter table public.bookings add column if not exists proof_image text;
alter table public.bookings add column if not exists payment_status text default 'Pending';
update public.bookings
set payment_reference = reference_number
where payment_reference is null and reference_number is not null;
update public.bookings
set pickup_address = address
where pickup_address is null and address is not null;

alter table public.bookings enable row level security;

drop policy if exists "Users manage own bookings"    on public.bookings;
drop policy if exists "Users can view own bookings"  on public.bookings;
drop policy if exists "Users can insert own bookings" on public.bookings;
drop policy if exists "Users can update own bookings" on public.bookings;
drop policy if exists "Users can delete own bookings" on public.bookings;

create policy "Users can view own bookings"
  on public.bookings for select
  using (auth.uid() = user_id);

create policy "Users can insert own bookings"
  on public.bookings for insert
  with check (auth.uid() = user_id);

create policy "Users can update own bookings"
  on public.bookings for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own bookings"
  on public.bookings for delete
  using (auth.uid() = user_id);


-- ── Services table ─────────────────────────────────────────
create table if not exists public.services (
  id          uuid default gen_random_uuid(),
  name        text primary key,
  price       numeric(10,2) not null default 0,
  description text not null default ''
);

alter table public.services add column if not exists id uuid default gen_random_uuid();
update public.services set id = gen_random_uuid() where id is null;
alter table public.services add column if not exists price numeric(10,2) not null default 0;
alter table public.services add column if not exists description text not null default '';
create unique index if not exists services_id_unique on public.services(id);
create unique index if not exists services_name_unique on public.services(name);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid,
  user_id uuid,
  customer_name text,
  payment_method text,
  status text default 'pending',
  payment_status text default 'Pending',
  amount numeric(10,2) default 0,
  payment_reference text,
  reference_number text,
  payment_proof text,
  proof_image text,
  created_at timestamptz default now()
);

alter table public.payments add column if not exists booking_id uuid;
alter table public.payments add column if not exists user_id uuid;
alter table public.payments add column if not exists customer_name text;
alter table public.payments add column if not exists payment_method text;
alter table public.payments add column if not exists status text default 'pending';
alter table public.payments add column if not exists payment_status text default 'Pending';
alter table public.payments add column if not exists amount numeric(10,2) default 0;
alter table public.payments add column if not exists payment_reference text;
alter table public.payments add column if not exists reference_number text;
alter table public.payments add column if not exists payment_proof text;
alter table public.payments add column if not exists proof_image text;
alter table public.payments add column if not exists created_at timestamptz default now();
update public.payments
set status = lower(replace(coalesce(nullif(status, ''), payment_status, 'pending'), ' ', '_'));
update public.payments
set status = 'paid'
where status in ('completed', 'verified');
alter table public.payments drop constraint if exists payments_status_check;
alter table public.payments
  add constraint payments_status_check
  check (status in ('pending', 'paid', 'cancelled'));

alter table public.services enable row level security;

drop policy if exists "Public can view services" on public.services;
create policy "Public can view services"
  on public.services for select
  using (true);


-- ── Admin RLS policies (service role bypasses RLS, but add for anon reads) ──

-- Allow service role full access to profiles
drop policy if exists "Admin full access profiles" on public.profiles;
create policy "Admin full access profiles"
  on public.profiles for all
  using (true)
  with check (true);

-- Allow service role full access to bookings
drop policy if exists "Admin full access bookings" on public.bookings;
create policy "Admin full access bookings"
  on public.bookings for all
  using (true)
  with check (true);

-- Machines: public read, service role write
alter table public.machines enable row level security;

drop policy if exists "Public can view machines" on public.machines;
create policy "Public can view machines"
  on public.machines for select
  using (true);

drop policy if exists "Admin full access machines" on public.machines;
create policy "Admin full access machines"
  on public.machines for all
  using (true)
  with check (true);

-- Seed default machines if table is empty
insert into public.machines (id, machine_number, name, status, load_type, enabled)
select * from (values
  (1, 1, 'Machine 1', 'Available', 'Light',  true),
  (2, 2, 'Machine 2', 'Available', 'Medium', true),
  (3, 3, 'Machine 3', 'In Use',    'Heavy',  true),
  (4, 4, 'Machine 4', 'Available', 'Light',  true),
  (5, 5, 'Machine 5', 'Available', 'Medium', true),
  (6, 6, 'Machine 6', 'In Use',    'Heavy',  true),
  (7, 7, 'Machine 7', 'Available', 'Medium', true),
  (8, 8, 'Machine 8', 'Available', 'Light',  true)
) as v(id, machine_number, name, status, load_type, enabled)
where not exists (select 1 from public.machines limit 1);


-- ── Verify ──────────────────────────────────────────────────
select tablename, policyname, cmd
from pg_policies
where schemaname = 'public'
order by tablename, cmd;
