-- ============================================================
-- FreshWash — Complete Fix Migration
-- Run this ONCE in: Supabase Dashboard → SQL Editor → New Query
-- Safe to re-run (all statements use IF NOT EXISTS / IF EXISTS)
-- ============================================================

-- ── 1. PROFILES ─────────────────────────────────────────────
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar       text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS otp_code     text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS otp_expiry   timestamptz;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_verified  boolean NOT NULL DEFAULT false;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone        text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS address      text;

-- ── 2. MACHINES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.machines (
  id             integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  machine_number integer PRIMARY KEY,
  name           text    NOT NULL DEFAULT '',
  status         text    NOT NULL DEFAULT 'Available',
  load_type      text    NOT NULL DEFAULT 'Medium',
  enabled        boolean NOT NULL DEFAULT true,
  updated_at     timestamptz DEFAULT now()
);

ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS id         integer;
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS name       text;
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS status     text    NOT NULL DEFAULT 'Available';
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS load_type  text    NOT NULL DEFAULT 'Medium';
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS enabled    boolean NOT NULL DEFAULT true;
ALTER TABLE public.machines ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Normalise any bad status values before adding the constraint
UPDATE public.machines
SET status = 'Available'
WHERE status NOT IN ('Available', 'In Use', 'Disabled');

-- Drop old constraint if it exists, then re-add cleanly
ALTER TABLE public.machines DROP CONSTRAINT IF EXISTS machines_status_check;
ALTER TABLE public.machines
  ADD CONSTRAINT machines_status_check
  CHECK (status IN ('Available', 'In Use', 'Disabled'));

-- Sync id = machine_number for rows that have no id yet
UPDATE public.machines SET id = machine_number
WHERE id IS NULL AND machine_number IS NOT NULL;

UPDATE public.machines
SET name = COALESCE(NULLIF(name, ''), 'Machine ' || machine_number::text)
WHERE name IS NULL OR name = '';

UPDATE public.machines SET enabled = false WHERE status = 'Disabled';

CREATE UNIQUE INDEX IF NOT EXISTS machines_id_unique ON public.machines(id);

-- RLS
ALTER TABLE public.machines ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view machines"   ON public.machines;
DROP POLICY IF EXISTS "Admin full access machines" ON public.machines;
CREATE POLICY "Public can view machines"   ON public.machines FOR SELECT USING (true);
CREATE POLICY "Admin full access machines" ON public.machines FOR ALL    USING (true) WITH CHECK (true);

-- Seed default machines only if table is empty
INSERT INTO public.machines (id, machine_number, name, status, load_type, enabled)
SELECT * FROM (VALUES
  (1, 1, 'Machine 1', 'Available', 'Light',  true),
  (2, 2, 'Machine 2', 'Available', 'Medium', true),
  (3, 3, 'Machine 3', 'In Use',    'Heavy',  true),
  (4, 4, 'Machine 4', 'Available', 'Light',  true),
  (5, 5, 'Machine 5', 'Available', 'Medium', true),
  (6, 6, 'Machine 6', 'In Use',    'Heavy',  true),
  (7, 7, 'Machine 7', 'Available', 'Medium', true),
  (8, 8, 'Machine 8', 'Available', 'Light',  true)
) AS v(id, machine_number, name, status, load_type, enabled)
WHERE NOT EXISTS (SELECT 1 FROM public.machines LIMIT 1);

-- ── 3. BOOKINGS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.bookings (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          uuid        REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  full_name        text        NOT NULL,
  phone            text        NOT NULL DEFAULT '',
  address          text        NOT NULL DEFAULT '',
  pickup_address   text,
  service_type     text        NOT NULL,
  machine          text,
  load_type        text,
  pickup_date      date        NOT NULL,
  pickup_time      time        NOT NULL,
  weight           numeric(6,2) NOT NULL DEFAULT 0,
  total_price      numeric(10,2),
  total_amount     numeric(10,2),
  delivery_option  text        DEFAULT 'Pickup',
  delivery_type    text        DEFAULT 'pickup',
  delivery_fee     numeric     NOT NULL DEFAULT 0,
  delivery_status  text        NOT NULL DEFAULT 'Not Started',
  payment_method   text,
  payment_status   text        DEFAULT 'Pending',
  payment_reference text,
  reference_number text,
  payment_proof    text,
  proof_image      text,
  notes            text,
  status           text        NOT NULL DEFAULT 'Pending',
  out_for_delivery_email_sent boolean DEFAULT false,
  delivered_email_sent        boolean DEFAULT false,
  created_at       timestamptz DEFAULT now()
);

-- Add every column individually so existing tables get patched too
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS phone            text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS address          text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS pickup_address   text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS service_type     text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS machine          text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS load_type        text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS weight           numeric(6,2);
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS total_price      numeric(10,2);
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS total_amount     numeric(10,2);
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS delivery_option  text DEFAULT 'Pickup';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS delivery_type    text DEFAULT 'pickup';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS delivery_fee     numeric NOT NULL DEFAULT 0;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS delivery_status  text NOT NULL DEFAULT 'Not Started';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS payment_method   text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS payment_status   text DEFAULT 'Pending';
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS payment_reference text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS reference_number text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS payment_proof    text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS proof_image      text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS notes            text;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS out_for_delivery_email_sent boolean DEFAULT false;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS delivered_email_sent        boolean DEFAULT false;
ALTER TABLE public.bookings ADD COLUMN IF NOT EXISTS created_at       timestamptz DEFAULT now();

-- Back-fill derived columns
UPDATE public.bookings SET pickup_address = address
WHERE pickup_address IS NULL AND address IS NOT NULL;

UPDATE public.bookings SET total_amount = total_price
WHERE total_amount IS NULL AND total_price IS NOT NULL;

UPDATE public.bookings SET delivery_fee = 0
WHERE delivery_fee IS NULL;

-- Delivery status constraint (safe re-add)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'bookings_delivery_status_check'
  ) THEN
    ALTER TABLE public.bookings
      ADD CONSTRAINT bookings_delivery_status_check
      CHECK (delivery_status IN ('Not Started', 'Preparing', 'Out for Delivery', 'Delivered'));
  END IF;
END $$;

-- RLS
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users manage own bookings"     ON public.bookings;
DROP POLICY IF EXISTS "Users can view own bookings"   ON public.bookings;
DROP POLICY IF EXISTS "Users can insert own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Users can update own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Users can delete own bookings" ON public.bookings;
DROP POLICY IF EXISTS "Admin full access bookings"    ON public.bookings;

CREATE POLICY "Users can view own bookings"
  ON public.bookings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own bookings"
  ON public.bookings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own bookings"
  ON public.bookings FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own bookings"
  ON public.bookings FOR DELETE USING (auth.uid() = user_id);
CREATE POLICY "Admin full access bookings"
  ON public.bookings FOR ALL USING (true) WITH CHECK (true);

-- ── 4. PAYMENTS ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payments (
  id             uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id     uuid        NOT NULL,
  user_id        uuid        NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  customer_name  text        NOT NULL DEFAULT '',
  payment_method text        NOT NULL DEFAULT '',
  payment_status text        NOT NULL DEFAULT 'Pending',
  amount         numeric     NOT NULL DEFAULT 0,
  payment_proof  text,
  proof_of_payment text,
  date           timestamptz DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS user_id          uuid        DEFAULT '00000000-0000-0000-0000-000000000000';
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS customer_name    text        NOT NULL DEFAULT '';
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS payment_method   text        NOT NULL DEFAULT '';
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS payment_status   text        NOT NULL DEFAULT 'Pending';
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS amount           numeric     NOT NULL DEFAULT 0;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS payment_proof    text;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS proof_of_payment text;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS date             timestamptz DEFAULT now();
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS created_at       timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_payments_created_at  ON public.payments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payments_booking_id  ON public.payments (booking_id);

-- RLS
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin full access payments" ON public.payments;
CREATE POLICY "Admin full access payments"
  ON public.payments FOR ALL USING (true) WITH CHECK (true);

-- ── 5. SERVICES ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.services (
  name        text PRIMARY KEY,
  price       numeric(10,2) NOT NULL DEFAULT 0,
  description text          NOT NULL DEFAULT ''
);

ALTER TABLE public.services ADD COLUMN IF NOT EXISTS price       numeric(10,2) NOT NULL DEFAULT 0;
ALTER TABLE public.services ADD COLUMN IF NOT EXISTS description text          NOT NULL DEFAULT '';

ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view services"    ON public.services;
DROP POLICY IF EXISTS "Admin full access services"  ON public.services;
CREATE POLICY "Public can view services"   ON public.services FOR SELECT USING (true);
CREATE POLICY "Admin full access services" ON public.services FOR ALL    USING (true) WITH CHECK (true);

-- ── 6. PROFILES RLS ─────────────────────────────────────────
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own profile"   ON public.profiles;
DROP POLICY IF EXISTS "Users can insert own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Admin full access profiles"   ON public.profiles;

CREATE POLICY "Users can view own profile"
  ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert own profile"
  ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile"
  ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
CREATE POLICY "Admin full access profiles"
  ON public.profiles FOR ALL USING (true) WITH CHECK (true);

-- ── 7. VERIFY ───────────────────────────────────────────────
SELECT
  t.table_name,
  c.column_name,
  c.data_type,
  c.column_default,
  c.is_nullable
FROM information_schema.tables t
JOIN information_schema.columns c ON c.table_name = t.table_name AND c.table_schema = 'public'
WHERE t.table_schema = 'public'
  AND t.table_name IN ('bookings', 'machines', 'payments', 'profiles', 'services')
ORDER BY t.table_name, c.ordinal_position;
